name: nuplan
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.4
  - pip:
    - -r requirements.txt -i https://mirrors.bfsu.edu.cn/pypi/web/simple
    - -r requirements_torch.txt
    - -r requirements_submission.txt
