scenario_type_sampling_weights:
  # scenario_name: scenario_type_weights
  # If a scenario types weight is not specified by default its weight is 1.0.
  # To sample with a lower probability set a weight lower than 1.0
  # To sample with a higher probability set a weight higher than 1.0
  enable: true
  scenario_type_weights:
    unknown: 1.0
    on_traffic_light_intersection: 1.0
    stationary: 1.0
    traversing_intersection: 1.0
    medium_magnitude_speed: 1.0
    near_long_vehicle: 1.0

scenario_type_loss_weights:
  unknown: 1.0
