ml_planner:
  _target_: nuplan.planning.simulation.planner.ml_planner.ml_planner.MLPlanner
  _convert_: 'all'

  model_config: ${model}  # Dictionary key from existing planner model config (e.g. raster_model)
  checkpoint_path: ${oc.env:NUPLAN_HOME}/my_fabulous_model.ckpt  # Path to trained model checkpoint
  thread_safe: true
